# Generated by Django 4.2.1 on 2023-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marke', models.CharField(max_length=100)),
                ('Modelis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valstybinis_NR', models.CharField(help_text='ABC123', max_length=6)),
                ('VIN_kodas', models.CharField(max_length=30)),
                ('klientas', models.CharField(max_length=100)),
                ('Automobilio_modelis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobilis.automobilio_modelis')),
            ],
        ),
    ]
