# Generated by Django 4.2.1 on 2023-05-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobilis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilio_modelis',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobilių modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
    ]
