# Generated by Django 4.2.1 on 2023-05-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automobilis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('kaina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('suma', models.IntegerField()),
                ('automobilis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobilis.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kiekis', models.CharField(max_length=255)),
                ('Kaina', models.CharField(max_length=255)),
                ('Paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzsakymas.paslauga')),
                ('Uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzsakymas.uzsakymas')),
            ],
        ),
    ]
